// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using testRequestRabbitMQ.BLL;

#nullable disable

namespace testRequestRabbitMQ.Migrations
{
    [DbContext(typeof(TestDbContext))]
    partial class TestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("testRequestRabbitMQ.BLL.RequestAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExitTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("OrdsDurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("OrdsEntryTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrdsException")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrdsExceptionMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OrdsExitTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrdsStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrdsUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RequestAuditLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
